---
name: module3_task1
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: le te instalojme paketat
        run: cd module3_task1 && sudo ./setup.sh
      - name: Make build
        run: make build -C module3_task1
...